# Triggered only after MR is created/modified/closed and on master
.common_only: &common_only
  only:
    - master
    - merge_requests
    - schedules
    - triggers

stages:
  - build
  - deploy

image: $CI_DOCS_DOCKER_IMAGE


build:
  stage: build
  tags: ['ace-x86_64']
  <<: *common_only
  before_script:
    - apt update && apt install -y git librsvg2-bin
    - pip3 install -r requirements.txt
  script:
    # checkout on the specified version if needed
    - |
      if [ -n "$TARGET_VERSION" ]; then
        echo -e "\n========== DOING CHECKOUT ON VERSION ============"
        echo "$TARGET_VERSION"
        git checkout "$TARGET_VERSION"
      fi
    - echo -en "\nhtml_js_files = [ '$ANNOTANT' ]" >> source/conf.py
    - make html
    - rm -R build/html/_sources
    - make text
    - for file in $(find build/text -type f -name '*.txt'); do mv "$file" "${file%.txt}.rst.txt"; done
    - mv build/text build/html/_sources
    - tar cf $CI_DOCS_ARCHIVE -C build/html/ .
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE

deploy:
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  stage: deploy
  tags: ['docs']
  <<: *common_only
  except:
    - triggers
  script: echo 'Deploying docs'
  artifacts:
    paths:
      - $CI_DOCS_ARCHIVE
